library(tidyverse) 
library(mgcv)
library(bestNormalize)
library(ggplot2)
library(tidymv)
library(voxel)
library(ggeffects)
library(egg)
library(patchwork)
library(dotwhisker)
library(broom)
library(scales)
library(Hmisc)
library(mgcViz)
library(fastshap)

## Load data
model_data <- read.csv("Colston_COVID-19_in_the_Andes_data.csv")
summary(model_data)

## Normalize skewed variables
skewed <- c("Precipitation", "Wind", "Accessibility", "Density")
normPredict <- function(mod) {
  predict(orderNorm(mod))
}
model_data <- model_data %>% 
  mutate(across(all_of(skewed), .fns = list(ORQ = ~normPredict(.x))))
## Specify factor variables
model_data$ID <- as.factor(model_data$ID)
model_data$Region <- as.factor(model_data$Region)
## fit model
covid_model<-mgcv::gam(Rt ~ 
                  s(Temperature,bs="cr",fx=TRUE, k = 4)
                  + s(Humidity,bs="cr",fx=TRUE, k = 4)
                  + s(Radiation,bs="cr",fx=TRUE, k = 4)        
                  + s(Wind_ORQ,bs="cr",fx=TRUE, k = 4)
                  + s(Moisture,bs="cr",fx=TRUE, k = 4)
                  + s(Precipitation_ORQ,bs="cr",fx=TRUE, k = 4)
                  + s(Policy,bs="cr",fx=TRUE, k = 4)
                  + s(Density_ORQ,bs="cr",fx=TRUE, k = 4)
                  + s(Accessibility_ORQ,bs="cr",fx=TRUE, k = 4)
                  + s(Elderly,bs="cr",fx=TRUE, k = 4)
                  + s(Residential,bs="cr",fx=TRUE, k = 4)
                  + Region                  
                  , data=model_data, family=gaussian(link=log), method = "REML"
                  ,correlation = corCAR1(value = 0.07, form = ~ date | ID)
                  )
summary(covid_model)
## Get predictions and accumulated local effects
Temperature.effect <- ggpredict(covid_model, terms = "Temperature")
Temperature.ale <- ALE(covid_model, "Temperature", type = "response",  oind = 1)
mean(abs(Temperature.ale$ALE$ALE$y), na.rm = TRUE)
Precipitation_ORQ.effect <- ggpredict(covid_model, terms = "Precipitation_ORQ")
Precipitation_ORQ.ale <- ALE(covid_model, "Precipitation_ORQ", type = "response",  oind = 1)
mean(abs(Precipitation_ORQ.ale$ALE$ALE$y))
Moisture.effect <- ggpredict(covid_model, terms = "Moisture")
Moisture.ale <- ALE(covid_model, "Moisture", type = "response",  oind = 1)
mean(abs(Moisture.ale$ALE$ALE$y))
Radiation.effect <- ggpredict(covid_model, terms = "Radiation")
Radiation.ale <- ALE(covid_model, "Radiation", type = "response",  oind = 1)
mean(abs(Radiation.ale$ALE$ALE$y))
Humidity.effect <- ggpredict(covid_model, terms = "Humidity")
Humidity.ale <- ALE(covid_model, "Humidity", type = "response",  oind = 1)
mean(abs(Humidity.ale$ALE$ALE$y))
Wind_ORQ.effect <- ggpredict(covid_model, terms = "Wind_ORQ")
Wind_ORQ.ale <- ALE(covid_model, "Wind_ORQ", type = "response",  oind = 1)
mean(abs(Wind_ORQ.ale$ALE$ALE$y))
Accessibility_ORQ.effect <- ggpredict(covid_model, terms = "Accessibility_ORQ")
Accessibility_ORQ.ale <- ALE(covid_model, "Accessibility_ORQ", type = "response",  oind = 1)
mean(abs(Accessibility_ORQ.ale$ALE$ALE$y))
Policy.effect <- ggpredict(covid_model, terms = "Policy")
Policy.ale <- ALE(covid_model, "Policy", type = "response",  oind = 1)
mean(abs(Policy.ale$ALE$ALE$y))
Density_ORQ.effect <- ggpredict(covid_model, terms = "Density_ORQ")
Density_ORQ.ale <- ALE(covid_model, "Density_ORQ", type = "response",  oind = 1)
mean(abs(Density_ORQ.ale$ALE$ALE$y))
Elderly.effect <- ggpredict(covid_model, terms = "Elderly")
Elderly.ale <- ALE(covid_model, "Elderly", type = "response",  oind = 1)
mean(abs(Elderly.ale$ALE$ALE$y))
Residential.effect <- ggpredict(covid_model, terms = "Residential")
Residential.ale <- ALE(covid_model, "Residential", type = "response",  oind = 1)
mean(abs(Residential.ale$ALE$ALE$y))
Region.effect <- broom::tidy(covid_model,parametric=T,)